
// Resource Filtering
export const FILTER_BY_PROGRESS_CURRENT = 'FILTER_BY_PROGRESS_CURRENT';
export const FILTER_BY_PROGRESS_PAST = 'FILTER_BY_PROGRESS_PAST';
export const FILTER_BY_PROGRESS_FUTURE = 'FILTER_BY_PROGRESS_FUTURE';

// Adding a Resource
export const ADD_RESOURCE_OPEN_DIALOG = 'ADD_RESOURCE_OPEN_DIALOG';
export const ADD_RESOURCE_CLOSE_DIALOG = 'ADD_RESOURCE_CLOSE_DIALOG';
export const ADD_RESOURCE_SUBMIT_DIALOG = 'ADD_RESOURCE_SUBMIT_DIALOG';
export const ADD_RESOURCE_PRIORITY_EDIT = 'ADD_RESOURCE_PRIORITY_EDIT';
export const ADD_RESOURCE_PROGRESS_EDIT = 'ADD_RESOURCE_PROGRESS_EDIT';
