
// Resource Filtering
export const FILTER_BY_PROGRESS_CURRENT = 'FILTER_BY_PROGRESS_CURRENT';
export const FILTER_BY_PROGRESS_PAST = 'FILTER_BY_PROGRESS_PAST';
export const FILTER_BY_PROGRESS_FUTURE = 'FILTER_BY_PROGRESS_FUTURE';
